### ISSUE TITLE
Build error with VS2019/msbuild on Windows

### ISSUE THREAD

**Issue by YasserAsmi** [craflin/libnstd#19]
Reporting this issue which is happening, but it is more of an excuse for sending a DM to say... Bravo, you have built an awesome library, libnstd! And more importantly, the principles you laid out and completely valid criticisms of STL.  What a mess C++ has become.  I have very similar feelings and very surprisingly very similar coding style :)

> cmake .
> msbuild ALL_BUILD.vcxproj

....

  Future.cpp
  Library.cpp
  Log.cpp
  Math.cpp
F:\src\ref\libnstd\include\nstd/Base.hpp(64,14): error C2084: function 'void *operator new(size_t,void *) noexcept' already has a body
 [F:\src\ref\libnstd\src\nstd.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\vcruntime_new.h(166): message : see p
revious definition of 'new' [F:\src\ref\libnstd\src\nstd.vcxproj]
F:\src\ref\libnstd\include\nstd/Base.hpp(65,13): error C2084: function 'void operator delete(void *,void *) noexcept' already has a bo
dy [F:\src\ref\libnstd\src\nstd.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\vcruntime_new.h(172): message : see p
revious definition of 'delete' [F:\src\ref\libnstd\src\nstd.vcxproj]
  Memory.cpp
  Monitor.cpp

**Comment by craflin** [comment]
I've fixed the issue in the master branch.

Kind regards,
  Colin.
